#! /bin/sh

nohup chromium --no-startup-window &

nohup $HOME/.config/polybar/launch.sh

nohup /usr/bin/kbdd

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

